### ISSUE TITLE
Release for changes related to Italia DLC

### ISSUE THREAD

**Issue by elkrejzi** [Art-Stea1th/DiscoveryMapHelper#4]
Hi,

I saw your workshop post on why you can't upload the mod there. I'd be grateful if you uploaded a version to the https://github.com/Art-Stea1th/DiscoveryMapHelper/releases page like you've done with previous versions, until the workshop issue is resolved.

Kind regards.

**Comment by Art-Stea1th** [comment]
Hi,
you can find it [here](https://github.com/Art-Stea1th/DiscoveryMapHelper/releases/tag/1.6.1712).

Regards.

**Comment by elkrejzi** [comment]
Works like a charm, thank you.

**Comment by Art-Stea1th** [comment]
Now also updated in the Steam Workshop.
